package com.customerservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-20T18:00:53.671+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://customerservice.com/", name = "CustomerService")
//@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

    @Oneway
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://customerservice.com/", className = "com.customerservice.UpdateCustomer")
    @WebMethod
    public void updateCustomer(
        @WebParam(name = "customer", targetNamespace = "")
        com.customerservice.Customer customer
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCustomersByName", targetNamespace = "http://customerservice.com/", className = "com.customerservice.GetCustomersByName")
    @WebMethod
    @ResponseWrapper(localName = "getCustomersByNameResponse", targetNamespace = "http://customerservice.com/", className = "com.customerservice.GetCustomersByNameResponse")
    public java.util.List<com.customerservice.Customer> getCustomersByName(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    ) throws NoSuchCustomerException;
}
