
package com.customerservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-20T18:00:53.594+05:30
 * Generated source version: 2.6.8
 */

@WebFault(name = "NoSuchCustomer", targetNamespace = "http://customerservice.com/")
public class NoSuchCustomerException extends Exception {
    
    private com.customerservice.NoSuchCustomer noSuchCustomer;

    public NoSuchCustomerException() {
        super();
    }
    
    public NoSuchCustomerException(String message) {
        super(message);
    }
    
    public NoSuchCustomerException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchCustomerException(String message, com.customerservice.NoSuchCustomer noSuchCustomer) {
        super(message);
        this.noSuchCustomer = noSuchCustomer;
    }

    public NoSuchCustomerException(String message, com.customerservice.NoSuchCustomer noSuchCustomer, Throwable cause) {
        super(message, cause);
        this.noSuchCustomer = noSuchCustomer;
    }

    public com.customerservice.NoSuchCustomer getFaultInfo() {
        return this.noSuchCustomer;
    }
}
