package org.apache.headers;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-30T22:14:36.937+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://apache.org/headers", name = "headerTester")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HeaderTester {

    @WebMethod
    public void outHeader(
        @WebParam(partName = "me", name = "outHeader", targetNamespace = "http://apache.org/headers")
        OutHeader me,
        @WebParam(partName = "the_response", mode = WebParam.Mode.OUT, name = "outHeaderResponse", targetNamespace = "http://apache.org/headers")
        javax.xml.ws.Holder<OutHeaderResponse> theResponse,
        @WebParam(partName = "header_info", mode = WebParam.Mode.OUT, name = "SOAPHeaderInfo", targetNamespace = "http://apache.org/headers", header = true)
        javax.xml.ws.Holder<SOAPHeaderData> headerInfo
    );

    @WebResult(name = "inHeaderResponse", targetNamespace = "http://apache.org/headers", partName = "the_response")
    @WebMethod
    public InHeaderResponse inHeader(
        @WebParam(partName = "me", name = "inHeader", targetNamespace = "http://apache.org/headers")
        InHeader me,
        @WebParam(partName = "header_info", name = "SOAPHeaderInfo", targetNamespace = "http://apache.org/headers", header = true)
        SOAPHeaderData headerInfo
    );

    @WebResult(name = "inoutHeaderResponse", targetNamespace = "http://apache.org/headers", partName = "the_response")
    @WebMethod
    public InoutHeaderResponse inoutHeader(
        @WebParam(partName = "me", name = "inoutHeader", targetNamespace = "http://apache.org/headers")
        InoutHeader me,
        @WebParam(partName = "header_info", mode = WebParam.Mode.INOUT, name = "SOAPHeaderInfo", targetNamespace = "http://apache.org/headers", header = true)
        javax.xml.ws.Holder<SOAPHeaderData> headerInfo
    );
}
