
package com.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T12:57:47.634+05:30
 * Generated source version: 2.6.8
 * 
 */
public final class IAccount_AccountPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.com/", "AccountService");

    private IAccount_AccountPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AccountService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AccountService ss = new AccountService(wsdlURL, SERVICE_NAME);
        IAccount port = ss.getAccountPort();  
        
        {
        System.out.println("Invoking updateAsync...");
        java.lang.String _updateAsync_arg0 = "_updateAsync_arg0-933478609";
        Response<com.server.UpdateResponse> _updateAsync__return = port.updateAsync(_updateAsync_arg0);
        System.out.println("updateAsync.result=" + _updateAsync__return);


        }
        {
        System.out.println("Invoking updateAsync...");
        java.lang.String _updateAsync_arg0 = "_updateAsync_arg01377308662";
        AsyncHandler<com.server.UpdateResponse> _updateAsync_asyncHandler = null;
        Future<?> _updateAsync__return = port.updateAsync(_updateAsync_arg0, _updateAsync_asyncHandler);
        System.out.println("updateAsync.result=" + _updateAsync__return);


        }
        {
        System.out.println("Invoking update...");
        java.lang.String _update_arg0 = "_update_arg0-20459648";
        port.update(_update_arg0);


        }
        {
        System.out.println("Invoking getDetailsAsync...");
        double _getDetailsAsync_arg0 = 0.6843040645565482;
        java.lang.String _getDetailsAsync_arg1 = "_getDetailsAsync_arg1-2110562161";
        Response<com.server.GetDetailsResponse> _getDetailsAsync__return = port.getDetailsAsync(_getDetailsAsync_arg0, _getDetailsAsync_arg1);
        System.out.println("getDetailsAsync.result=" + _getDetailsAsync__return);


        }
        {
        System.out.println("Invoking getDetailsAsync...");
        double _getDetailsAsync_arg0 = 0.8795514723490462;
        java.lang.String _getDetailsAsync_arg1 = "_getDetailsAsync_arg11402061285";
        AsyncHandler<com.server.GetDetailsResponse> _getDetailsAsync_asyncHandler = null;
        Future<?> _getDetailsAsync__return = port.getDetailsAsync(_getDetailsAsync_arg0, _getDetailsAsync_arg1, _getDetailsAsync_asyncHandler);
        System.out.println("getDetailsAsync.result=" + _getDetailsAsync__return);


        }
        {
        System.out.println("Invoking getDetails...");
        double _getDetails_arg0 = 0.33543926701524973;
        java.lang.String _getDetails_arg1 = "_getDetails_arg1-19032297";
        int _getDetails__return = port.getDetails(_getDetails_arg0, _getDetails_arg1);
        System.out.println("getDetails.result=" + _getDetails__return);


        }

        System.exit(0);
    }

}
