
package com.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Mon Nov 23 16:16:50 IST 2015
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "withdrawAmount", namespace = "http://server.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "withdrawAmount", namespace = "http://server.com/")

public class WithdrawAmount {

    @XmlElement(name = "arg0")
    private double arg0;

    public double getArg0() {
        return this.arg0;
    }

    public void setArg0(double newArg0)  {
        this.arg0 = newArg0;
    }

}

