
package com.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.8
 * Fri Jun 21 21:52:26 IST 2013
 * Generated source version: 2.6.8
 */

@XmlRootElement(name = "getDetails", namespace = "http://server.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDetails", namespace = "http://server.com/", propOrder = {"arg0", "arg1"})

public class GetDetails {

    @XmlElement(name = "arg0")
    private double arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;

    public double getArg0() {
        return this.arg0;
    }

    public void setArg0(double newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

}

