
package com.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Wed Oct 28 13:49:43 IST 2015
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "getBalance", namespace = "http://server.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBalance", namespace = "http://server.com/")

public class GetBalance {


}

