
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.customerservice;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-20T18:00:53.637+05:30
 * Generated source version: 2.6.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "CustomerServiceService",
                      portName = "CustomerServicePort",
                      targetNamespace = "http://customerservice.com/",
                      wsdlLocation = "http://localhost:8080/Cxf_WSDL_First/services/CustomerServicePort?wsdl",
                      endpointInterface = "com.customerservice.CustomerService")
                      
public class CustomerServiceImpl implements CustomerService {

    private static final Logger LOG = Logger.getLogger(CustomerServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.customerservice.CustomerService#updateCustomer(com.customerservice.Customer  customer )*
     */
    public void updateCustomer(com.customerservice.Customer customer) { 
        LOG.info("Executing operation updateCustomer");
        System.out.println(customer);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.customerservice.CustomerService#getCustomersByName(java.lang.String  name )*
     */
    public java.util.List<com.customerservice.Customer> getCustomersByName(java.lang.String name) throws NoSuchCustomerException    { 
        LOG.info("Executing operation getCustomersByName");
        System.out.println(name);
        try {
            java.util.List<com.customerservice.Customer> _return = new java.util.ArrayList<com.customerservice.Customer>();
            com.customerservice.Customer _returnVal1 = new com.customerservice.Customer();
            _returnVal1.setCustomerId(-336215928);
            _returnVal1.setName("Name345468968");
            java.util.List<java.lang.String> _returnVal1Address = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1AddressVal1 = "_returnVal1AddressVal577389920";
            _returnVal1Address.add(_returnVal1AddressVal1);
            _returnVal1.getAddress().addAll(_returnVal1Address);
            _returnVal1.setNumOrders(Integer.valueOf(-1434569155));
            _returnVal1.setRevenue(0.47580537542651147);
            _returnVal1.setTest(new java.math.BigDecimal("-7042991933038879310.8650704737780573868"));
            _returnVal1.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-06-20T17:56:58.077+05:30"));
            com.customerservice.CustomerType _returnVal1Type = com.customerservice.CustomerType.BUSINESS;
            _returnVal1.setType(_returnVal1Type);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchCustomerException("NoSuchCustomerException...");
    }

}
