
package com;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T14:13:42.153+05:30
 * Generated source version: 2.6.8
 */

@WebFault(name = "InvalidPOException", targetNamespace = "http://com/")
public class InvalidPOException_Exception extends Exception {
    
    private com.InvalidPOException invalidPOException;

    public InvalidPOException_Exception() {
        super();
    }
    
    public InvalidPOException_Exception(String message) {
        super(message);
    }
    
    public InvalidPOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidPOException_Exception(String message, com.InvalidPOException invalidPOException) {
        super(message);
        this.invalidPOException = invalidPOException;
    }

    public InvalidPOException_Exception(String message, com.InvalidPOException invalidPOException, Throwable cause) {
        super(message, cause);
        this.invalidPOException = invalidPOException;
    }

    public com.InvalidPOException getFaultInfo() {
        return this.invalidPOException;
    }
}
