package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T14:13:42.183+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://com/", name = "WarehouseImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface WarehouseImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "submitPO", targetNamespace = "http://com/", className = "com.SubmitPO")
    @WebMethod
    @ResponseWrapper(localName = "submitPOResponse", targetNamespace = "http://com/", className = "com.SubmitPOResponse")
    public com.ShipmentNotice submitPO(
        @WebParam(name = "arg0", targetNamespace = "")
        com.PurchaseOrder arg0
    ) throws InvalidPOException_Exception;
}
