
package com;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T14:13:42.091+05:30
 * Generated source version: 2.6.8
 * 
 */
public final class WarehouseImpl_WarehouseImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://com/", "WarehouseImplService");

    private WarehouseImpl_WarehouseImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WarehouseImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WarehouseImplService ss = new WarehouseImplService(wsdlURL, SERVICE_NAME);
        WarehouseImpl port = ss.getWarehouseImplPort();  
        
        {
        System.out.println("Invoking submitPO...");
        com.PurchaseOrder _submitPO_arg0 = new com.PurchaseOrder();
        java.util.List<com.Item> _submitPO_arg0ItemList = new java.util.ArrayList<com.Item>();
        com.Item _submitPO_arg0ItemListVal1 = new com.Item();
        _submitPO_arg0ItemListVal1.setItemID(2033703673);
        _submitPO_arg0ItemListVal1.setName("Name1643664936");
        _submitPO_arg0ItemListVal1.setPrice(0.28375274f);
        _submitPO_arg0ItemListVal1.setQuantity(-2063394903);
        _submitPO_arg0ItemList.add(_submitPO_arg0ItemListVal1);
        _submitPO_arg0.getItemList().addAll(_submitPO_arg0ItemList);
        _submitPO_arg0.setCustomerNumber("CustomerNumber57576078");
        _submitPO_arg0.setOrderNumber("OrderNumber-932760311");
        
        com.Item item2 = new com.Item();
        item2.setItemID(1234);
        item2.setName("MyItem");
        
        _submitPO_arg0.getItemList().add(item2);
        
        try {
            com.ShipmentNotice _submitPO__return = port.submitPO(_submitPO_arg0);
            System.out.println("submitPO.result=" + _submitPO__return);
        System.out.println("The ;lst returned is  "+ _submitPO__return.itemList);

        } catch (InvalidPOException_Exception e) { 
            System.out.println("Expected exception: InvalidPOException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
