
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T14:13:42.168+05:30
 * Generated source version: 2.6.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "WarehouseImplService",
                      portName = "WarehouseImplPort",
                      targetNamespace = "http://com/",
                      wsdlLocation = "http://localhost:8080/CXF_CustomTypes/services/WarehouseImplPort?wsdl",
                      endpointInterface = "com.WarehouseImpl")
                      
public class WarehouseImplImpl implements WarehouseImpl {

    private static final Logger LOG = Logger.getLogger(WarehouseImplImpl.class.getName());

    /* (non-Javadoc)
     * @see com.WarehouseImpl#submitPO(com.PurchaseOrder  arg0 )*
     */
    public com.ShipmentNotice submitPO(com.PurchaseOrder arg0) throws InvalidPOException_Exception    { 
        LOG.info("Executing operation submitPO");
        System.out.println(arg0);
        try {
            com.ShipmentNotice _return = new com.ShipmentNotice();
            java.util.List<com.Item> _returnItemList = new java.util.ArrayList<com.Item>();
            com.Item _returnItemListVal1 = new com.Item();
            _returnItemListVal1.setItemID(472215541);
            _returnItemListVal1.setName("Name-1221791762");
            _returnItemListVal1.setPrice(0.14183074f);
            _returnItemListVal1.setQuantity(180769362);
            _returnItemList.add(_returnItemListVal1);
            _return.getItemList().addAll(_returnItemList);
            _return.setCustomerNumber("CustomerNumber858500001");
            _return.setOrderNumber("OrderNumber-835490234");
            _return.setShipmentNumber("ShipmentNumber1850284515");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidPOException_Exception("InvalidPOException...");
    }

}
