package com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T14:13:42.191+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebServiceClient(name = "WarehouseImplService", 
                  wsdlLocation = "http://localhost:8080/CXF_CustomTypes/services/WarehouseImplPort?wsdl",
                  targetNamespace = "http://com/") 
public class WarehouseImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com/", "WarehouseImplService");
    public final static QName WarehouseImplPort = new QName("http://com/", "WarehouseImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/CXF_CustomTypes/services/WarehouseImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WarehouseImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CXF_CustomTypes/services/WarehouseImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WarehouseImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WarehouseImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WarehouseImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WarehouseImpl
     */
    @WebEndpoint(name = "WarehouseImplPort")
    public WarehouseImpl getWarehouseImplPort() {
        return super.getPort(WarehouseImplPort, WarehouseImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WarehouseImpl
     */
    @WebEndpoint(name = "WarehouseImplPort")
    public WarehouseImpl getWarehouseImplPort(WebServiceFeature... features) {
        return super.getPort(WarehouseImplPort, WarehouseImpl.class, features);
    }

}
