
package com.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T00:22:03.585+05:30
 * Generated source version: 2.6.8
 * 
 */
 
public class IAccount_AccountPort_Server{

    protected IAccount_AccountPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IAccountImpl();
        String address = "http://localhost:8080/CXF_AsyncService/services/AccountPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IAccount_AccountPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
