package com.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-21T12:19:30.385+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://server.com/", name = "Account")
//@XmlSeeAlso({ObjectFactory.class})
public interface Account {

    @RequestWrapper(localName = "update", targetNamespace = "http://server.com/", className = "com.server.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://server.com/", className = "com.server.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDetails", targetNamespace = "http://server.com/", className = "com.server.GetDetails")
    @WebMethod
    @ResponseWrapper(localName = "getDetailsResponse", targetNamespace = "http://server.com/", className = "com.server.GetDetailsResponse")
    public int getDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
