
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T22:23:35.613+05:30
 * Generated source version: 2.6.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "AccountService",
                      portName = "AccountPort",
                      targetNamespace = "http://server.com/",
                      wsdlLocation = "http://localhost:8080/Cxf_Basic_Authetication/services/AccountPort?wsdl",
                      endpointInterface = "com.server.Account")
                      
public class AccountImpl implements Account {

    private static final Logger LOG = Logger.getLogger(AccountImpl.class.getName());

    /* (non-Javadoc)
     * @see com.server.Account#processData(int  arg0 ,)double  arg1 )*
     */
    public java.lang.String processData(int arg0,double arg1) { 
        LOG.info("Executing operation processData");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-110725841";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.server.Account#update(int  arg0 ,)java.lang.String  arg1 )*
     */
    public void update(int arg0,java.lang.String arg1) { 
        LOG.info("Executing operation update");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.server.Account#getName(int  arg0 )*
     */
    public java.lang.String getName(int arg0) { 
        LOG.info("Executing operation getName");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1802055762";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
