package com.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T22:23:35.630+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://server.com/", name = "Account")
@XmlSeeAlso({ObjectFactory.class})
public interface Account {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processData", targetNamespace = "http://server.com/", className = "com.server.ProcessData")
    @WebMethod
    @ResponseWrapper(localName = "processDataResponse", targetNamespace = "http://server.com/", className = "com.server.ProcessDataResponse")
    public java.lang.String processData(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://server.com/", className = "com.server.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://server.com/", className = "com.server.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://server.com/", className = "com.server.GetName")
    @WebMethod
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://server.com/", className = "com.server.GetNameResponse")
    public java.lang.String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
