
package com.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import javax.xml.ws.Service;
import javax.xml.ws.handler.MessageContext;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T22:23:35.562+05:30
 * Generated source version: 2.6.8
 * 
 */
public final class Account_AccountPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.com/", "AccountService");

    private Account_AccountPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
       
         
        URL fileURL = Account_AccountPort_Client.class.getResource("/account.wsdl");
        
        //URL fileURL = AccountService.WSDL_LOCATION;
        System.out.println("Url "+fileURL.getFile());       

        
        Service service = Service.create(fileURL, SERVICE_NAME);
        //AccountService service = new AccountService(wsdlURL, SERVICE_NAME);
        
        
        Account port = service.getPort(Account.class);  
        
        //set the user,password on request context used to access the protected resource
        
        BindingProvider bp = (BindingProvider) port;
        bp.getRequestContext().put(BindingProvider.USERNAME_PROPERTY, "tomcat");
        bp.getRequestContext().put(BindingProvider.PASSWORD_PROPERTY, "tomcat");
        
         
        /*//set the  user,password on current request context
        Map<String, Object> req_ctx = ((BindingProvider)port).getRequestContext();
        req_ctx.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "http://localhost:9090/Cxf_Basic_Authetication/services/AccountPort");
     
        Map<String, List<String>> headers = new HashMap<String, List<String>>();
        headers.put("Username", Collections.singletonList("tomcat"));
        headers.put("Password", Collections.singletonList("tomcat"));
        req_ctx.put(MessageContext.HTTP_REQUEST_HEADERS, headers);      
        */
       
        
        {
        System.out.println("Invoking processData...");
        int _processData_arg0 = -664375319;
        double _processData_arg1 = 0.5479055856692978;
        java.lang.String _processData__return = port.processData(_processData_arg0, _processData_arg1);
        System.out.println("processData.result=" + _processData__return);


        }
        {
        System.out.println("Invoking update...");
        int _update_arg0 = 1132431908;
        java.lang.String _update_arg1 = "_update_arg1119357522";
        port.update(_update_arg0, _update_arg1);


        }
        {
        System.out.println("Invoking getName...");
        int _getName_arg0 = 2045558106;
        java.lang.String _getName__return = port.getName(_getName_arg0);
        System.out.println("getName.result=" + _getName__return);


        }

        System.exit(0);
    }

}
