
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.8
 * Sat Jun 22 13:56:36 IST 2013
 * Generated source version: 2.6.8
 */

@XmlRootElement(name = "InvalidPOException", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvalidPOException", namespace = "http://com/", propOrder = {"detail", "message"})

public class InvalidPOExceptionBean {

    private java.lang.String detail;
    private java.lang.String message;

    public java.lang.String getDetail() {
        return this.detail;
    }

    public void setDetail(java.lang.String newDetail)  {
        this.detail = newDetail;
    }

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

