
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.8
 * Sat Jun 22 10:25:29 IST 2013
 * Generated source version: 2.6.8
 */

@XmlRootElement(name = "submitPO", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "submitPO", namespace = "http://com/")

public class SubmitPO {

    @XmlElement(name = "arg0")
    private com.PurchaseOrder arg0;

    public com.PurchaseOrder getArg0() {
        return this.arg0;
    }

    public void setArg0(com.PurchaseOrder newArg0)  {
        this.arg0 = newArg0;
    }

}

