package com.server;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-22T00:22:03.569+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://server.com/", name = "IAccount")
@XmlSeeAlso({ObjectFactory.class})
public interface IAccount {

    @RequestWrapper(localName = "update", targetNamespace = "http://server.com/", className = "com.server.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://server.com/", className = "com.server.UpdateResponse")
    @WebMethod(operationName = "update")
    public Response<com.server.UpdateResponse> updateAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://server.com/", className = "com.server.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://server.com/", className = "com.server.UpdateResponse")
    @WebMethod(operationName = "update")
    public Future<?> updateAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.server.UpdateResponse> asyncHandler
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://server.com/", className = "com.server.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://server.com/", className = "com.server.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "getDetails", targetNamespace = "http://server.com/", className = "com.server.GetDetails")
    @ResponseWrapper(localName = "getDetailsResponse", targetNamespace = "http://server.com/", className = "com.server.GetDetailsResponse")
    @WebMethod(operationName = "getDetails")
    public Response<com.server.GetDetailsResponse> getDetailsAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "getDetails", targetNamespace = "http://server.com/", className = "com.server.GetDetails")
    @ResponseWrapper(localName = "getDetailsResponse", targetNamespace = "http://server.com/", className = "com.server.GetDetailsResponse")
    @WebMethod(operationName = "getDetails")
    public Future<?> getDetailsAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.server.GetDetailsResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDetails", targetNamespace = "http://server.com/", className = "com.server.GetDetails")
    @WebMethod
    @ResponseWrapper(localName = "getDetailsResponse", targetNamespace = "http://server.com/", className = "com.server.GetDetailsResponse")
    public int getDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
