<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WarehouseImplService" targetNamespace="http://com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://com/" schemaLocation="warehouseimpl_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="submitPO">
    <wsdl:part name="parameters" element="tns:submitPO">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="submitPOResponse">
    <wsdl:part name="parameters" element="tns:submitPOResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InvalidPOException">
    <wsdl:part name="InvalidPOException" element="tns:InvalidPOException">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="WarehouseImpl">
    <wsdl:operation name="submitPO">
      <wsdl:input name="submitPO" message="tns:submitPO">
    </wsdl:input>
      <wsdl:output name="submitPOResponse" message="tns:submitPOResponse">
    </wsdl:output>
      <wsdl:fault name="InvalidPOException" message="tns:InvalidPOException">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WarehouseImplServiceSoapBinding" type="tns:WarehouseImpl">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="submitPO">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="submitPO">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="submitPOResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvalidPOException">
        <soap:fault name="InvalidPOException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WarehouseImplService">
    <wsdl:port name="WarehouseImplPort" binding="tns:WarehouseImplServiceSoapBinding">
      <soap:address location="http://localhost:8080/CXF_CustomTypes/services/WarehouseImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
