
package com.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Wed Oct 28 16:09:16 IST 2015
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "getUserResponse", namespace = "http://server.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUserResponse", namespace = "http://server.com/")

public class GetUserResponse {

    @XmlElement(name = "return")
    private com.server.User _return;

    public com.server.User getReturn() {
        return this._return;
    }

    public void setReturn(com.server.User new_return)  {
        this._return = new_return;
    }

}

