
package com.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Wed Oct 28 16:09:16 IST 2015
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "updateUser", namespace = "http://server.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateUser", namespace = "http://server.com/")

public class UpdateUser {

    @XmlElement(name = "arg0")
    private com.server.User arg0;

    public com.server.User getArg0() {
        return this.arg0;
    }

    public void setArg0(com.server.User newArg0)  {
        this.arg0 = newArg0;
    }

}

