
package com.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-21T12:19:30.307+05:30
 * Generated source version: 2.6.8
 * 
 */
public final class Account_AccountPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.com/", "AccountService");

    private Account_AccountPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AccountService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AccountService ss = new AccountService(wsdlURL, SERVICE_NAME);
        Account port = ss.getAccountPort();  
        System.out.println("The account implementation on client is  "+port);
        
        {
        System.out.println("Invoking update...");
        java.lang.String _update_arg0 = "User_Asoka";
        port.update(_update_arg0);


        }
        {
        System.out.println("Invoking getDetails...");
        double _getDetails_arg0 = 1245.897;
        java.lang.String _getDetails_arg1 = "My User Name";
        int _getDetails__return = port.getDetails(_getDetails_arg0, _getDetails_arg1);
        System.out.println("getDetails.result=" + _getDetails__return);


        }

        System.exit(0);
    }

}
