package com.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-23T03:04:14.981+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://server.com/", name = "Login")
@XmlSeeAlso({ObjectFactory.class})
public interface Login {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processData", targetNamespace = "http://server.com/", className = "com.server.ProcessData")
    @WebMethod
    @ResponseWrapper(localName = "processDataResponse", targetNamespace = "http://server.com/", className = "com.server.ProcessDataResponse")
    public java.lang.String processData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processLogin", targetNamespace = "http://server.com/", className = "com.server.ProcessLogin")
    @WebMethod
    @ResponseWrapper(localName = "processLoginResponse", targetNamespace = "http://server.com/", className = "com.server.ProcessLoginResponse")
    public boolean processLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
