
package com.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-23T03:04:14.911+05:30
 * Generated source version: 2.6.8
 * 
 */
public final class Login_LoginPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.com/", "Login");

    private Login_LoginPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Login_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Login_Service ss = new Login_Service(wsdlURL, SERVICE_NAME);
        Login port = ss.getLoginPort();  
        
        {
        System.out.println("Invoking processData...");
        java.lang.String _processData_arg0 = "_processData_arg01653002174";
        int _processData_arg1 = -1517244009;
        double _processData_arg2 = 0.09150447099658998;
        java.lang.String _processData__return = port.processData(_processData_arg0, _processData_arg1, _processData_arg2);
        System.out.println("processData.result=" + _processData__return);


        }
        {
        System.out.println("Invoking processLogin...");
        java.lang.String _processLogin_arg0 = "_processLogin_arg0-2107274140";
        java.lang.String _processLogin_arg1 = "_processLogin_arg1-1190897109";
        boolean _processLogin__return = port.processLogin(_processLogin_arg0, _processLogin_arg1);
        System.out.println("processLogin.result=" + _processLogin__return);


        }

        System.exit(0);
    }

}
