package com.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-23T03:04:14.991+05:30
 * Generated source version: 2.6.8
 * 
 */
@WebServiceClient(name = "Login", 
                  wsdlLocation = "http://localhost:8080/Cxf_SSL_Service/services/LoginPort?wsdl",
                  targetNamespace = "http://server.com/") 
public class Login_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.com/", "Login");
    public final static QName LoginPort = new QName("http://server.com/", "LoginPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Cxf_SSL_Service/services/LoginPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Login_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Cxf_SSL_Service/services/LoginPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Login_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Login_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Login_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "LoginPort")
    public Login getLoginPort() {
        return super.getPort(LoginPort, Login.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "LoginPort")
    public Login getLoginPort(WebServiceFeature... features) {
        return super.getPort(LoginPort, Login.class, features);
    }

}
